# Generated by Django 4.2.4 on 2023-08-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_maisto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hotwheels',
        ),
    ]
