# Generated by Django 4.2.4 on 2023-08-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_hotwheels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tomica',
        ),
    ]
